### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by landaisbenj**
More informativ

### CODE REVIEW

**Comment by paphko** [comment]
Thank you @landaisbenj !

**Comment by landaisbenj** [comment]
:) you're welcome :D I take advantage of your presence to see if it is possible to display an angle with the doors or windows?

**Comment by landaisbenj** [comment]
Like this:  
image

**Comment by paphko** [comment]
This is not yet possible. At the moment, the code only works for right angles because a simple rectangle is drawn: https://github.com/paphko/mmm-openhabfloorplan/blob/c293c5ad219112affb48547aac076ed358ed7ccf/mmm-openhabfloorplan.js#L220
For wings, it's this function: https://github.com/paphko/mmm-openhabfloorplan/blob/c293c5ad219112affb48547aac076ed358ed7ccf/mmm-openhabfloorplan.js#L229
Feel free to implement arbitrary angles and provide another pull request :-)

**Comment by landaisbenj** [comment]
Thank you for you're reply. I don't really good in dev but i can try. (I think one day i must try to create a module for domoticz server to adapt your work)

**Comment by landaisbenj** [comment]
Another thing, which language it is? To learn lol

**Pull request merged**
